name: Copy terrascan.yml to Repos

on:
  issues:
   type:
    -closed
    -opened

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install Requests Library
        run: pip install requests

    

      - name: Copy terrascan.yml
        run: python .github/workflows/automate.py
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
- name: Send Teams Notification
  if: ${{ always() }}
  env:
    TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
  run: |
    if [[ "${{ job.status }}" == "success" ]]; then
      status_text="succeeded"
      status_color="#36a64f"
    fi

    if [[ "${{ job.status }}" == "failure" ]]; then
      status_text="failed"
      status_color="#d9534f"
    fi

    project_key="${{ steps.get_project_key.outputs.project_key }}"
    report_url="http://20.113.139.49:9000/dashboard?id=$project_key"
    echo "Report URL: $report_url"
    workflow_file_name="${GITHUB_WORKFLOW}"
    workflow_file_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}?check_suite_focus=true"
    payload="{
      \"@type\": \"MessageCard\",
      \"themeColor\": \"${status_color}\",
      \"title\": \"GitHub Actions Workflow\",
      \"text\": \"Workflow has ${status_text}: ${{ github.repository }}\",
      \"sections\": [
        {
          \"activityTitle\": \"SonarQube Analysis\",
          \"activitySubtitle\": \"${status_text}\",
          \"activityImage\": \"https://www.sonarqube.org/logos/index/favicon.png\",
          \"facts\": [
            {
              \"name\": \"Repository\",
              \"value\": \"${{ github.repository }}\"
            },
            {
              \"name\": \"Report\",
              \"value\": \"[SonarQube Analysis Report](${report_url})\"
            },
            {
              \"name\": \"Workflow File\",
              \"value\": \"[${workflow_file_name}](${workflow_file_url})\"
            }
          ]
        }
      ]
    }"

    curl -X POST -H "Content-Type: application/json" -d "$payload" $TEAMS_WEBHOOK_URL
