name: Add Workflow File to Repos

on:
  issues:
    type:
     -opened
     -closed
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight UTC

jobs:
  add_workflow:
    runs-on: ubuntu-latest

    steps:
  
      - name: Retrieve Repository Names
        env:
          GH_TOKEN: ${{secrets.TEST_TOKEN}}
        run: |
          ORGANIZATION="Prasanna-source31"
          REPO_NAMES=$(gh api /orgs/$ORGANIZATION/repos --jq '.[].name')

      - name: Add Workflow File to Repos
        env:
          GH_TOKEN: ${{secrets.TEST_TOKEN}}
        run: |
          WORKFLOW_PATH=".github/workflows/terrascan.yml"  # Change this path if needed
          WORKFLOW_CONTENT=$(cat $WORKFLOW_PATH | base64 -w 0)
          
          for repo in $REPO_NAMES; do
            gh api -X PUT /repos/$ORGANIZATION/$repo/contents/$WORKFLOW_PATH \
              -F message="Add main workflow" \
              -F content="$WORKFLOW_CONTENT" \
              -F branch=main
            echo "Workflow file added to $repo"
          done
