on:
  push:
    branches:
      - main

jobs:
  terrascan_job_aws:
    runs-on: ubuntu-latest
    name: terrascan-action AWS Policies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Terrascan with AWS Policies
        id: terrascan_aws
        uses: tenable/terrascan-action@main
        with:
          iac_type: 'terraform'
          iac_version: 'v14'
          policy_type: 'aws'
          only_warn: true
      - name: Save Terrascan Output (AWS) to File
        run: echo "${{ steps.terrascan_aws.outputs.stdout }}" > terrascan_aws_output.json
      - name: Upload Terrascan Output (AWS) as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: terrascan_aws_output
          path: terrascan_aws_output.json

  terrascan_job_general:
    runs-on: ubuntu-latest
    name: terrascan-action General Policies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Terrascan with General Policies
        id: terrascan_general
        uses: tenable/terrascan-action@main
        with:
          iac_type: 'terraform'
          iac_version: 'v14'
          policy_type: 'general'
          only_warn: true
      - name: Save Terrascan Output (General) to File
        run: echo "${{ steps.terrascan_general.outputs.stdout }}" > terrascan_general_output.json
      - name: Upload Terrascan Output (General) as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: terrascan_general_output
          path: terrascan_general_output.json
- name: Send Teams Notification
  if: ${{ always() }}
  env:
    TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
  run: |
    if [[ "${{ job.status }}" == "success" ]]; then
      status_text="succeeded"
      status_color="#36a64f"
    fi

    if [[ "${{ job.status }}" == "failure" ]]; then
      status_text="failed"
      status_color="#d9534f"
    fi

    project_key="${{ steps.get_project_key.outputs.project_key }}"
    report_url="http://20.113.139.49:9000/dashboard?id=$project_key"
    echo "Report URL: $report_url"
    workflow_file_name="${GITHUB_WORKFLOW}"
    workflow_file_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}?check_suite_focus=true"
    payload="{
      \"@type\": \"MessageCard\",
      \"themeColor\": \"${status_color}\",
      \"title\": \"GitHub Actions Workflow\",
      \"text\": \"Workflow has ${status_text}: ${{ github.repository }}\",
      \"sections\": [
        {
          \"activityTitle\": \"SonarQube Analysis\",
          \"activitySubtitle\": \"${status_text}\",
          \"activityImage\": \"https://www.sonarqube.org/logos/index/favicon.png\",
          \"facts\": [
            {
              \"name\": \"Repository\",
              \"value\": \"${{ github.repository }}\"
            },
            {
              \"name\": \"Report\",
              \"value\": \"[SonarQube Analysis Report](${report_url})\"
            },
            {
              \"name\": \"Workflow File\",
              \"value\": \"[${workflow_file_name}](${workflow_file_url})\"
            }
          ]
        }
      ]
    }"

    curl -X POST -H "Content-Type: application/json" -d "$payload" $TEAMS_WEBHOOK_URL
